name: Build and Release Nexus Launcher

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Create secrets.json file
        shell: bash
        run: |
              echo "{\"SGDB_API_KEY\":\"${{ secrets.SGDB_API_KEY }}\", \"RAWG_API_KEY\":\"${{ secrets.RAWG_API_KEY }}\", \"YOUTUBE_API_KEY\":\"${{ secrets.YOUTUBE_API_KEY }}\"}" > src/secrets.json

      - name: Build and Publish for Windows
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --x64 --arm64 --publish always

      - name: Build and Publish for Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --linux --x64 --arm64 --publish always

      - name: Build and Publish for macOS
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --mac --universal --publish always